version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: food_postgres
    environment:
      POSTGRES_USER: food
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: food_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data: